name: pdf_arabic_translator
description: Personal Android PDF translator with multi-key Groq and OpenRouter failover.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  file_picker: 13.1.0
  file_saver: 0.6.0
  flutter_secure_storage: 11.2.0
  google_mlkit_text_recognition: 0.17.1
  http: 1.6.0
  path_provider: 2.1.6
  pdf: 3.13.1
  pdfx: 2.11.0
  printing: 5.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
